import "Constants"

# Fastlane has an issue with Swift Package Manager and might timeout while loading. This sets the timeout to 10 minutes.
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

# Set default platform to iOS.
default_platform(:ios)

platform :ios do
	lane :build do
    		run_tests
    		cert
    		sigh 
    		gym
  	end 

	lane :alpha do
		build
		pilot
  		increment_build_number
	end

	lane :release do
		build
		deliver
  		increment_build_number
	end
	
end